### PR TITLE
Google Python Style Guide?

### PR DESCRIPTION
**Pull request by delirious-lettuce**
_The changes made in this PR follow the [Google Python Style Guide](https://google.github.io/styleguide/pyguide.html)._

The main difference is changing the indentation from 2 space to 4 space. There are a bunch more changes that could make this code more Pythonic but I thought I'd hold off to see how this first PR was received.

* [Use 4 space indentation](https://google.github.io/styleguide/pyguide.html?showone=Indentation#Indentation)
* [Remove trailing semicolons](https://google.github.io/styleguide/pyguide.html?showone=Semicolons#Semicolons)
* [Use 2 blank lines between top-level definitions](https://google.github.io/styleguide/pyguide.html?showone=Blank_Lines#Blank_Lines)
* Remove excess blank line at EOF

### CODE REVIEW

**Comment by ifratric** [comment]
I welcome the other changes, but according to the Google internal style guide I'm looking at, "Indent your code blocks with 2 spaces.". Except for "implied line continuation" (that part is the same in both versions). Not sure why the internal one is out of sync with the one you linked to.

**Comment by delirious-lettuce** [comment]
@ifratric ,

If I had to guess (please correct me if I am wrong!), I would say it has to do with internal VS external (open source) projects. I would guess that closed source/internal projects at Google are to follow whatever internal style guide you are referring to but once this project was made open-source it would seem logical to adhere to common Python standards for open-source code.

* https://github.com/google/styleguide/issues/140#issuecomment-322235626

Not only is four space indentation is the standard for Python ([PEP8 link](http://pep8.org/#indentation)) but `snake_case` function names are also standard according to [PEP8](http://pep8.org/) & [Google Python Style Guide](https://google.github.io/styleguide/pyguide.html?showone=Naming#Naming). I didn't start changing the function names yet (wanted to see how this PR was received first) but I can gladly send some more PRs to fix those and other minor issues.

I admit that I have not read every section of the Google Python Style Guide thoroughly but, from the parts I have read, it seems tightly coupled with PEP8. Following these common standards does make it easier for contributors from the open-source world.

Thanks for the reply!

**Comment by ifratric** [comment]
Fair.

The second problem with the spaces thing is that currently the patch only addresses one of the 2 python source files. This would mean that by accepting it now, the spacing would become inconsistent. I don't have strong opinion on 2 vs. 4 spaces indentation, but I would like it to be consistent within the project. I suggest applying the spacing equally to both source files.

**Comment by delirious-lettuce** [comment]
@ifratric ,

I didn't want to make any changes to `grammar.py` until seeing getting feedback on the original changes. I have updated `grammar.py` with the above commit to use 4 space indentation and fix other minor things like trailing semicolons and whitespace issues (full summary in commit message). Adhering to a common styleguide can help to make the code more consistent and easier for other Python developers to contribute to. While going through this file I noticed a few things that might need addressing but I will use separate issues/pull requests for those.

Let me know what you think!

**Comment by ivanfratric** [comment]
Looks good, I can test & merge when I'm back in the office on Monday (posting from another account).

**Comment by delirious-lettuce** [comment]
@ivanfratric ,

Sounds good, let me know if any other changes are needed.

Thanks for your time!

**Comment by ifratric** [comment]
Aaaand done. Thanks!

**Comment by delirious-lettuce** [comment]
@ifratric ,

No problem!

**Pull request merged**
